# -*- coding: utf-8 -*-
"""Cotacao_Dolar.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yqPILbh65tjvRHBek4MHTnYkO3aPJGOk
"""

import requests

import json

cotacoes = requests.get("https://economia.awesomeapi.com.br/last/USD-BRL,EUR-BRL,BTC-BRL")
cotacoes = cotacoes.json()
cotacao_dolar = cotacoes['USDBRL']['bid']
#print(cotacoes)
print(cotacao_dolar)